### ISSUE TITLE
Disable user namespaces (needed for containers) by default

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_hardening#5]
Add the following to `/data/common.yaml` to disable user namespaces (needed for containers) by default:
```
profile_hardening::sysctl::settings:
  user.max_user_namespaces:
    target: "/etc/sysctl.d/60-ncsa-default.conf"
    value: 0
```
